---
- hosts: localhost
  connection: local

  tasks:

  - name: manage user accounts
    import_tasks: users.yml

  - name: symlink config files
    file:
      path: "/home/{{ my_user }}/{{ item | basename }}"
      src: "{{ item }}"
      state: link
      force: yes
    with_fileglob: "files/.*"

  - name: symlink bash scripts folder
    file:
      path: "/home/{{ my_user}}/.bashsrc"
      src: files/.bashsrc
      state: link
      force: yes

  - name: install my favourite packages
    yum:
      name: "{{ yum_install_packages }}"
      state: present

  - name: download gotop
    unarchive:
      src: https://github.com/xxxserxxx/gotop/releases/download/v3.5.2/gotop_v3.5.2_linux_amd64.tgz
      dest: /tmp/
      remote_src: yes
    when: install_gotop | bool 
        
  - name: install gotop
    copy:
      src: /tmp/gotop
      dest: /usr/local/bin/gotop
      mode: 777
    when: install_gotop | bool 