---
- hosts: localhost
  connection: local

  tasks:

  - name: symlink everything
    file:
      path: "/home/{{ username }}/{{ item | basename }}"
      src: "{{ item }}"
      state: link
      force: yes
    with_fileglob: "files/.*"

  - name: install my favourite packages
    yum:
      name: "{{ yum_install_packages }}"
      state: installed

  - name: download gotop
    unarchive:
      src: https://github.com/xxxserxxx/gotop/releases/download/v3.5.2/gotop_v3.5.2_linux_amd64.tgz
      dest: gotop.rpm
      remote_src: yes
        
  - name: install gotop
    yum:
      name: gotop.rpm
      state: installed